### ISSUE TITLE
The Midnight Club

### ISSUE THREAD

**Issue by Cricketx818** [W1lsonCodes/legacy-map-issue-tracker#1]
Whitelisted Group name : The Midnight Club

Locations and descriptions : rim paint, bennys, the repair shop at the docks and if possible part of highways( since we'll do most of our races on highways)

Color : midnight purple and if not possible then midnight blue( or black if nobody took it yet)

https://cdn.discordapp.com/attachments/640617451083661345/683112316367405079/Screenshot_4-1.png

https://cdn.discordapp.com/attachments/640617451083661345/683112316576989252/Screenshot_3-1-1.png

**Comment by W1lsonCodes** [comment]
I have Added this for you

**Wilson**
