### ISSUE TITLE
Pirados MC

### ISSUE THREAD

**Issue by Cricketx818** [W1lsonCodes/legacy-map-issue-tracker#3]
Gang Name: Pirados MC

Description Of Location: Sandy Shores, Weed Process and splitting ChopShop with The Lost.(Tsunami wise, Since the clubs are EU/NA based)

Color What is your Gang Color: Yellow/Black

Reason:  It's our territory. We have our legal business up in sandy as well as our illegal.

https://cdn.discordapp.com/attachments/683219291616706565/683244801621098498/Pirados_MC.png

**Comment by W1lsonCodes** [comment]
This has been added

**Wilson**
