### ISSUE TITLE
Young Bloods

### ISSUE THREAD

**Issue by Cricketx818** [W1lsonCodes/legacy-map-issue-tracker#4]
Gang Name: Young Bloods

Description Of Location: The location is called the "barrio" which Young Bloods has taken over and live there. 

Color What is your Gang Color: WHITE

Reason: For a long time Young Bloods looked for a place they could call a home. Young Bloods is most known for being a street gang, where people hire them for all kinds of jobs. Murders, kidnapping, drug imports etc.. So they needed a place which such crimes can be done without anyone being able to hear it.

For a long time the Barrio has been under control of hispanic gangs but this has come to an end. There has been different gangs who have tried to maintain the Barrio for years but have never done it right. And it’s time for a gang that can hold their own, to run this place.
Young Bloods saw a chance and took it as fast as they could. The Barrio is a perfect spot for the YBS as it is easy to do their Jobs. 

The Barrio is great in different ways to do crime. The Barrio is located south of Los Santos which it’s easy to come and go to places. There are no limits of what crime that can be done there. Right next to the Barrio is an abandoned slaughter place. Most of the time they take their enemy there because the walls are so thick so gunshots and streams cannot be heard from the outside. 

After a while the Police started to worry about the Barrio because they have had so many reports of shots being fired. So they started to control around the area. At that time the young bloods were the only ones that lived there so they all knew the police got eyes on them. So they decided to buy more blocks and rent out apartments to other people so it would look more neutral than it is. 

The Barrio still keeps many dark secrets which is not to be told to the man on the outside and are known to just a few Young Bloods members.

https://i.gyazo.com/thumb/1200/89733d8bb8eb8d9705a4f0e57102567d-png.jpg

**Comment by W1lsonCodes** [comment]
This has been added

**Wilson**
